docker_user:
  id: 1001
  gid: 1001
  name: dockeruser
  group: dockeruser

media: 
  gid: 321

docker_compose_file_mask: 0664
docker_compose_dir_mask: 0775
zfs_dir: /mnt/tank
data_dir: /opt
storage_dir: /mnt/storage

user: nate
home: /home/{{ user }}

TZ: America/New_York
