- name: "Creating install directory for tubesync"
  file:
    path: "{{ data_dir }}/tubesync"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
    mode: "{{ docker_compose_dir_mask }}"
  become: true

- name: Installing compose file for tubesync
  template:
    src: files/docker-compose.yml
    dest: "{{ data_dir }}/tubesync/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
  become: true

- name: Deploying Tubesync
  docker_compose:
    project_src: "{{ data_dir }}/tubesync/"
    files: 
      - docker-compose.yml

- name: Copying over db.sqlite3 for tubesync
  copy:
    src: files/db.sqlite3
    dest: "{{ data_dir }}/tubesync/config"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"

