version: "3"
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /opt/flame:/app/data
    ports:
      - 5005:5005
    environment: 
      - PASSWORD={{ flame.password }}
    restart: unless-stopped
