- name: Create install directory for psitransfer
  file:
    path: "{{ data_dir }}/psitransfer"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
    mode: "{{ docker_compose_dir_mask }}"
  become: true

- name: Install compose file for psitransfer
  template:
    src: files/docker-compose.yml
    dest: "{{ data_dir }}/psitransfer/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
  become: true


- name: Deploying psitransfer
  docker_compose:
    project_src: "{{ data_dir }}/psitransfer/"
    files: 
      - docker-compose.yml
