version: '3'
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    environment: 
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.gid }}
      - TZ=America/New_York
    ports: 
      - 4848:4848
    volumes: 
      - ./config:/config
      - "{{ zfs_dir }}/fuse/backups/youtube:/downloads"
    restart: unless-stopped  
