- name: Create install directory for vaultwarden
  file:
    path: "{{ data_dir }}/vaultwarden"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
    mode: "{{ docker_compose_dir_mask }}"
  become: true

- name: Install compose file for vaultwarden
  template:
    src: files/docker-compose.yml
    dest: "{{ data_dir }}/vaultwarden/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
  become: true

- name: Deploying Vaultwarden
  docker_compose:
    project_src: "{{ data_dir }}/vaultwarden/"
    files: 
      - docker-compose.yml
