api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
    proxyProtocol: 
      trustedIPs:
        - "10.1.10.1/32"
  websecure:
    address: :443
    http:
      #      middlewares:
      #         - floc-block@file // dont work dunno why
      tls:
        certResolver: letsencrypt
    proxyProtocol:
      trustedIPs:
        - "10.1.10.1/32"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/data/conf

certificatesResolvers:
  letsencrypt:
    acme:
      email: anon@xenoslabs.us
      storage: /etc/traefik/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
accessLog:
  filePath: "/var/log/traefik/access.log"
  filters:
    statusCodes:
      - "400-499"

tls:
  options:
    default:
      minVersion: VersionTLS12 
