version: "3.8"
networks:
  proxy:
    external: true
  wg-easy:
    ipam:
      config:
        -  subnet: 10.8.1.0/24
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=lhz46uh8av3muhesfanbkhvsedyuvhyymx.duckdns.org
      - PASSWORD=iRHrx@y7rjBdM2
      # Optional:
      # - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.1.126, 9.9.9.9
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      #- WG_PRE_UP=iptables -t nat -A POSTROUTING -j MASQUERADE -o eno1
      #- WG_PRE_DOWN=iptables -t nat -D POSTROUTING -j MASQUERADE -o eno1
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_PERSISTENT_KEEPALIVE=25
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    networks:
      proxy:
      wg-easy:
         ipv4_address: 10.8.1.2

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg-easy.rule=Host(`wg.xenoslabs.us`)"
      - "traefik.http.routers.wg-easy.entrypoints=websecure"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"
      - "traefik.docker.network=proxy"


