- name: Install OpenSSH
  package:
    name: openssh-server
  become: true

- name: Install SSH keys
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  loop:
    - ssh-keys/jinba.pub
    - ssh-keys/x1nano.pub

- name: Install SSH config
  template:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    backup: true
    mode: 0644
  become: true
  register: sshd_config

- name: Restart SSHD
  service:
    name: sshd
    state: reloaded
  become: true

- name: Enable SSH
  service:
    name: sshd
    enabled: true
  become: true
