- name: Make my user
  user:
    name: "{{ user }}"
    home: "{{ home }}"
    shell: /bin/bash
    system: true
    password: "{{ nubes.password }}"
    groups: "sudo"
  become: true

- name: Gimme sudo
  lineinfile:
    path: /etc/sudoers
    line: "{{ user }} ALL=(ALL) ALL"
  become: true 
