- name: Creating install directory for traefik
  file:
    path: "{{ data_dir }}/traefik"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
    mode: "{{ docker_compose_dir_mask }}"
  become: true

- name: Creating data directory for traefik
  file:
    path: "{{ data_dir }}/traefik/data"
    state: directory 
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"
    mode: "{{ docker_compose_dir_mask }}"

- name: Creating file provider directory for traefik
  file:
    path: "{{ data_dir }}/traefik/data/conf"
    state: directory
    mode: "{{ docker_compose_dir_mask }}"


- name: Installing traefik compose file
  template: 
    src: files/docker-compose.yml
    dest: "{{ data_dir }}/traefik/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"

- name: Installing traefik.yml
  template:
    src:  files/traefik.yml
    dest: "{{ data_dir }}/traefik/data/traefik.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.group }}"

- name: Installing base file provider
  template:
    src: files/base-file-provider.yml
    dest: "{{ data_dir }}/traefik/data/conf/main.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"

- name: Creating Traefik docker network
  docker_network:
    name: proxy

- name: Deploying Traefik
  docker_compose:
    project_src: "{{ data_dir }}/traefik/"
    files: 
      - docker-compose.yml
