- name: Install wireguard tools
  package:
    name: wireguard-tools
  become: true

- name: Install client config
  template:
    src: files/wg-proxy-client.conf
    dest: /etc/wireguard/cloud-proxy.conf
    mode: "0600"
  become: true
  register: wireguard_conf

- name: Enable wireguard service
  service:
    name: wg-quick@cloud-proxy
  become: true

- name: Restart wireguard service
  service: 
    name: wg-quick@cloud-proxy
    state: restarted
  when: wireguard_conf.changed
  become: true
